properties([
    parameters([
        booleanParam(defaultValue: false, description: 'Reset workspace', name: 'Reset workspace')
    ])
])

node {
    vcs_checkout()
    resolve_dependencies()
    build_project()
    chain_job tests
}